### PR TITLE
Remove redundant parsers

### PR DESCRIPTION
**Pull request by bfcarpio**
All of the following are already in [recipe-scrapers](https://github.com/hhursev/recipe-scrapers).

### CODE REVIEW

**Comment by poundifdef** [comment]
Is the version in `requirements.txt` correct for using these parsers?

**Comment by bfcarpio** [comment]
Probably would have worked, but I updated it anyways.

**Comment by poundifdef** [comment]
Hi - when I run this code locally, then it throws an error. Can you run the code locally and verify that all of the parsers still work?

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import parsers
  File "/Users/jgoel/github/plainoldrecipe/parsers/__init__.py", line 1, in <module>
    from parsers.smittenkitchen import Smittenkitchen
ModuleNotFoundError: No module named 'parsers.smittenkitchen'
```

**Comment by bfcarpio** [comment]
Sorry about that! I mixed up branches and repos when working with the changes. 

I've restored `smittenkitchen.com` so it uses the local parser.

I've rebased this PR onto master and tested that all other removed websites still work.

**Comment by poundifdef** [comment]
Closing this for now, as much of this has changed in the past 8 months. Would love to remove scrapers, I'd just want to test and ensure that the recipe-scrapers version has the same (or better) correctness compared to the parsers here - in some cases, we've made small corrections to the scrapers themsevles.

**Pull request closed without merging**
