### PR TITLE
Remove parsers with functioning upstream `recipe_parsers` equivalents

### PR DESCRIPTION
**Pull request by bcspragu**
[As discussed here](https://github.com/poundifdef/plainoldrecipe/issues/15#issuecomment-1892459748), this PR removes parsers with upstream equivalents in [recipe-scrapers](https://github.com/hhursev/recipe-scrapers).

I tested these out manually (via POR.com) and programmatically. Of the overlapping 11 parsers, 9 of them work identically, or are broken in POR and functional upstream. The remaining two are ones that remove douuble parens (`((e.g. this, on ingredient lists))`) in POR, whereas the upstream doesn't. For those two (`minimalistbaker`, `thewoksoflife`), I'll make those changes upstream first, then remove those here.

<details>
<summary>Full notes from testing</summary>

```
akispetretzikis.py
- Test URL: https://akispetretzikis.com/recipe/7120/choirino-frikase-sth-chytra-tachythtas
- One in POR doesn't work, confirmed in web UI
- RS one works

bowlofdelicious.py
- Confirmed they return same results (both extract json-ld)

chefkoch.py
- Confirmed they return same results (both extract json-ld)

fattoincasadabenedetta.py
- Test URL: https://www.fattoincasadabenedetta.it/ricetta/petto-di-pollo-impanato-allo-yogurt/
- One in POR doesn't work, confirmed in web UI
- RS one works

gimmesomeoven.py
- Test URL: https://www.gimmesomeoven.com/baked-tofu/
- One in POR doesn't work, confirmed in web UI
- RS one works

hostthetoast.py
- Confirmed they return same results (both extract json-ld)

kochbar.py
- Test URL: https://www.kochbar.de/rezept/586771/Veganes-Pistazien-Tiramisu.html
- One in POR doesn't work, confirmed in web UI
- RS one works

lovingitvegan.py
- Confirmed they return same results (both extract json-ld)

minimalistbaker.py
- RS one doesn't remove double parens
	- They do for some, [e.g. this one](https://github.com/hhursev/recipe-scrapers/blob/10a86fa60540407cae5875efc3802d1a69114d07/recipe_scrapers/norecipes.py#L30-L35)
	- Will contribute that fix upstream before touching this one

seriouseats.py
- Test URL: https://www.seriouseats.com/sriracha-recipe-from-scratch
- POR one strips too many characters off beginning, (e.g. `1. ce jalapeños`, `2. ck jar`)
- RS handles correctly

thewoksoflife.py
- Test URL: https://thewoksoflife.com/shrimp-egg-foo-young/
- RS one doesn't remove double parens, same as minimalistbaker, won't touch for now
```

</details>

### CODE REVIEW

**Review by poundifdef — CHANGES_REQUESTED** [review]
Thanks. This code does not run. Can you run plainoldrecipe locally and fix?

**Comment by bcspragu** [comment]
Ah, sorry about that, fixed and tested locally, runs now and upstream parsers are correctly used.

**Comment by poundifdef** [comment]
With the new code, the "description" is missing. For example in this url, there is a description at the top ("Fresh Ginger and Date Cookies with molasses make for a flavor-packed...") https://www.bowlofdelicious.com/spicy-ginger-date-cookies/

**Comment by bcspragu** [comment]
Ah, excellent catch. I hadn't checked `description`, looks like `bowlofdelicious` (and possibly others) are suffering from [this issue](https://github.com/hhursev/recipe-scrapers/issues/554).

The fix is easy, just:

```python
    def description(self):
        return self.schema.description()
```

on the scraper. I added it to `bowlofdelicious.py`, and got back `Fresh Ginger and Date Cookies with molasses make for a [...] perfect for Christmastime or anytime!`

I'll go through all the 9 scrapers above and double check all fields, not the subset I was spot-checking before (which didn't include `description`. I'll make those changes upstream before going further here.

**Comment by poundifdef** [comment]
Got it - thanks for chasing it down! I'll go ahead and merge your PR now (sans description) since it fixes a lot of broken code. We can add back in the descriptions over subsequent PRs.

**Comment by bcspragu** [comment]
Belatedly following up: I've sent out [an upstream fix](https://github.com/hhursev/recipe-scrapers/pull/999). Once that makes it's way into a release, I'll send you a PR to update your version of of the dep and then POR will be back where it was!

**Pull request merged**
