### PR TITLE
fixes issue-17: adds thatlowcarblife.com

### LINKED ISSUE #17: what sites are popular with plainoldrecipe but aren't supported yet
Would it be possible to log the sites that folks are trying to use and post statistics to help prioritize which parsers might be most useful?

### PR DESCRIPTION
**Pull request by chrispinkney**
Adds support for `https://thatlowcarblife.com/`. I tested it using about 7 randomly selected recipes from the site and it always displayed them as expected.

I'm also down to try and implement some sort of logging system to keep track of failed recipe scrape attempts so new parsers can in turn be developed, but I'm not sure how/if you'd even like this done, haha. It might be a fun challenge, so feel free to @ if you'd like it worked on.

Not much else to say! Hope you like it, let me know! 😀

### CODE REVIEW

**Comment by poundifdef** [comment]
Thanks for this!

I like the idea of logging and publicizing sites that aren't converted yet. There are two challenges, and maybe you have an idea:

1. I could do this using logs. But then I have to manually scrape/parse those logs from GCP and publish them somewhere, and  I am not ready to commit time to doing that!

2. We could log them into some sort of data store, but I don't have any sort of database running for storing this data. 

This is currently a stateless web application which is very low-maintenance on my part! So if you had an idea for how to expose this information without incurring extra hosting cost or manual maintenance, then I would be open to suggestions. Maybe there is something clever one could do with the GCP API to parse and expose these logs?

**Comment by chrispinkney** [comment]
Not a problem!

How about keeping a Google spreadsheet (which I've never used but imagine has a ton of fun analytics to work with) and just updating it with the `domain` that failed [just before here](https://github.com/poundifdef/plainoldrecipe/blob/master/main.py#L53)? I found [this which might be of help](https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html). Seems promising.

Or via use of a bot deployed on heroku's free tier (_but I don't think the free tier gives enough hours to cover the entire month, I tried to make a discord bot once and had that issue_) that updates a GitHub issue with unsupported domains?

I think Firebase also has a free option but I don't know anything about it (or about GCP tbh) beyond the name, haha.

firefox_2020-11-03_14-39-31

What do you think?

**Comment by poundifdef** [comment]
When testing, I did find one URL that didn't work: https://thatlowcarblife.com/big-mac-chaffle/

I notice that this site supports a JSON recipe format. In the source code, look for `<script type="application/ld+json">`. I wonder if that would be less error-prone to parse. You can see an example here: https://github.com/poundifdef/plainoldrecipe/blob/master/parsers/essenundtriken.py

You might also try inheriting code from `WpJsonRecipe`, as we do in `bowlofdelicious.py`.

Thanks for taking a look!

With respect to getting a list of analytics: sure, let's move the conversation into the issue itself!

**Comment by chrispinkney** [comment]
Ah I didn't even think to check whether the website supported JSON or not. Sorry for the stupid question, but does simply having a script tag in the html somewhere like the one you quoted me means the website supports JSON?

Either way, I imagine you don't have a list of recipes that you test for, right? I'm asking because I was just throwing random recipes that I found on their homepage at it and it always seemed to work. Is there something I should keep my eye out for that might fail to test against with my PR?

Sorry though! I'll get on it ASAP.

**Comment by chrispinkney** [comment]
Okay, how's this?

I re-implemented it using a JSON parser instead.

> You might also try inheriting code from WpJsonRecipe, as we do in bowlofdelicious.py.

I tried this too, but it didn't work out.

I tested this PR with the following sites and they all seemed to work:
```
https://thatlowcarblife.com/jalapeno-popper-chicken/
https://thatlowcarblife.com/sauteed-kale-and-brussels-sprouts/
https://thatlowcarblife.com/pumpkin-chaffles/
https://thatlowcarblife.com/sauteed-broccoli-with-bacon/
https://thatlowcarblife.com/instant-pot-cajun-ranch-chicken-soup/
https://thatlowcarblife.com/parmesan-roasted-green-beans/
https://thatlowcarblife.com/keto-taco-skillet/
https://thatlowcarblife.com/keto-cookie-dough/
https://thatlowcarblife.com/ranch-roasted-nuts
https://thatlowcarblife.com/keto-peanut-butter-mousse/
https://thatlowcarblife.com/big-mac-chaffle/
```

However `https://thatlowcarblife.com/big-mac-chaffle/` is being a pain. It's throws:

```Python
recipe['instructions'] = [i['text'] for i in soup['recipeInstructions']]
TypeError: string indices must be integers
``` 

and just refuses to behave like the rest of the recipes. I hope you're okay with the `try` block, personally I'm not but I don't really know how else to proceed with this that makes every other recipe else happy.

As always let me know!

**Comment by himynameisdave** [comment]
> _I'm also down to try and implement some sort of logging system to keep track of failed recipe scrape attempts so new parsers can in turn be developed, but I'm not sure how/if you'd even like this done_

@chrispinkney yeap logging sounds nice, I believe it's being discussed over in #17

**Comment by poundifdef** [comment]
This is excellent, thank you!

**Pull request merged**
