### PR TITLE
Refactor some json parsers into a common class.

### PR DESCRIPTION
**Pull request by jerjou**
This allows one to more easily add a new site that utilizes whatever wordpress plugin provides the nicely-structured recipe data.

Per #18

### CODE REVIEW

**Comment by jerjou** [comment]
Closing per [work in progress](https://github.com/poundifdef/plainoldrecipe/issues/18#issuecomment-653810568).

**Comment by poundifdef** [comment]
Hello! I like the idea of this PR. I would love for this to become a reality for plainoldrecipe. I would encourage you to re-open this pull request. I have some ideas for how I would prefer this code be structured, but I have no objection to this being included in this repository. Would you like to work with me to make this contribution a reality?

**Comment by poundifdef** [comment]
Hi! I like the direction of this PR. One thing that I would like to keep, architecturally, is for each recipe parser to have its own class. This way, there will be exactly one way that new parsers are introduced, rather than two ways (either via the "regular" mapping, or the `WP_JSON_PARSERS` mapping.)

One way to do this would be to subclass. That is, continue to keep your `WpJsonRecipe` class, but then a wordpress-based recipe would be defined as:

```
class Bowlofdelicious(WpJsonRecipe):
    pass
```

This would create more of these skeleton recipe classes, but would have the advantage of allowing us to keep a single map, `PARSERS`, and a single way of organizing recipe parsers, which I think is very useful for clarity.

**Comment by jerjou** [comment]
Makes sense.

**Comment by poundifdef** [comment]
This looks good. Happy to merge this, if you wouldn't mind fixing the conflicts (I just merged your other PR for adding `thewoksoflife.com`).

**Comment by jerjou** [comment]
Whoops - totally forgot this hasn't been resolved yet.
Question - do you use python2 or python3 here?

**Comment by poundifdef** [comment]
This is using Python 3.7

**Comment by jerjou** [comment]
Rebased to master

**Comment by poundifdef** [comment]
Hi! Apologies for being so late with this - have been in the process of changing jobs over the past month, so I haven't been spending quite so much time on this project. Your changes look great, going to merge now. Thank you!

**Pull request merged**
